import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './components/Providers'
import { authOptions } from './lib/auth'
import { getServerSession } from 'next-auth'
import  Image  from 'next/image';
import { Logout, Login } from './components/Buttons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <nav className='header'>
        <h1>GabChat</h1>
        
        {session ? 
           (
           <div className='log'>
          <Image src={session.user?.image as string} alt="" width={50} height={50}/>
         <Logout />
          </div>) : (
          <div className='log'>
         <Login />
          </div>)}

        
        </nav>
        <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
